export const STORAGE_KEYS = {
  settings: 'vf_settings',
  stats: 'vf_stats',
  characterLibrary: 'vf_character_lib',
  authIntent: 'vf_auth_intent',
  uidSetupRequired: 'vf_uid_setup_required',
  uiTheme: 'vf_ui_theme',
  uiDensity: 'vf_ui_density',
  uiFontScale: 'vf_ui_font_scale',
  uiMotionLevel: 'vf_ui_motion_level',
  studioSidebarMode: 'vf_studio_sidebar_mode',
  studioEditorMode: 'vf_studio_editor_mode',
  studioQueue: 'vf_studio_queue',
  labSession: 'vf_lab_session',
  labPreferences: 'vf_lab_preferences',
  labCapabilities: 'vf_lab_capabilities',
  labRuntimeDefaults: 'vf_lab_runtime_defaults',
  novelWorkspaceMeta: 'vf_novel_workspace_meta',
  novelWorkspaceMigration: 'vf_novel_workspace_migration',
  readerPreferences: 'vf_reader_preferences',
  localAdminSession: 'vf_local_admin_session',
  driveGoogleTokenCache: 'vf_drive_google_token_cache',
  clonedVoices: 'vf_clones',
  notifications: 'vf_notifications',
  notificationStateVersion: 'vf_notification_state_version',
  notificationPrefs: 'vf_notification_prefs',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
