export const STORAGE_KEYS = {
  settings: 'vf_settings',
  stats: 'vf_stats',
  characterLibrary: 'vf_character_lib',
  authIntent: 'vf_auth_intent',
  checkoutIntent: 'vf_checkout_intent',
  pendingSignupProfile: 'vf_pending_signup_profile',
  uidSetupRequired: 'vf_uid_setup_required',
  uiTheme: 'vf_ui_theme',
  uiBrandTheme: 'vf_ui_brand_theme',
  uiFontScale: 'vf_ui_font_scale',
  uiMotionLevel: 'vf_ui_motion_level',
  studioSidebarMode: 'vf_studio_sidebar_mode',
  studioEditorMode: 'vf_studio_editor_mode',
  studioDraftText: 'vf_studio_draft_text',
  studioDraftHistory: 'vf_studio_draft_history',
  workspaceActiveTab: 'vf_workspace_active_tab',
  studioRailTab: 'vf_studio_rail_tab',
  studioQueue: 'vf_studio_queue',
  studioSingleInflightGeneration: 'vf_studio_single_inflight_generation',
  studioSpeakerVcReferences: 'vf_studio_speaker_vc_references',
  novelWorkspaceMeta: 'vf_novel_workspace_meta',
  novelWorkspaceMigration: 'vf_novel_workspace_migration',
  regionHint: 'vf_region_hint',
  regionSource: 'vf_region_source',
  notifications: 'vf_notifications',
  notificationStateVersion: 'vf_notification_state_version',
  notificationPrefs: 'vf_notification_prefs',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
