export const API_ROUTE_FAMILIES = Object.freeze({
  account: '/api/v1/account',
  billing: '/api/v1/billing',
  studio: '/api/v1/studio',
  library: '/api/v1/library',
  publishing: '/api/v1/publishing',
  voiceClone: '/api/v1/voice-clone',
  admin: '/api/v1/admin',
  ops: '/api/v1/ops',
});

export const API_ROUTES = Object.freeze({
  account: {
    bootstrap: `${API_ROUTE_FAMILIES.account}/bootstrap`,
    profile: `${API_ROUTE_FAMILIES.account}/profile`,
    profileBootstrap: `${API_ROUTE_FAMILIES.account}/profile/bootstrap`,
    entitlements: `${API_ROUTE_FAMILIES.account}/entitlements`,
    generationHistory: `${API_ROUTE_FAMILIES.account}/generation-history`,
    notifications: `${API_ROUTE_FAMILIES.account}/notifications`,
    notificationPreferences: `${API_ROUTE_FAMILIES.account}/notification-preferences`,
    supportMessages: `${API_ROUTE_FAMILIES.account}/support/messages`,
    mySupportConversations: `${API_ROUTE_FAMILIES.account}/support/conversations/me`,
    delete: `${API_ROUTE_FAMILIES.account}/delete`,
    kyc: `${API_ROUTE_FAMILIES.account}/kyc`,
    withdrawals: `${API_ROUTE_FAMILIES.account}/withdrawals`,
    readerLegalAck: `${API_ROUTE_FAMILIES.account}/reader/legal-ack`,
  },
  billing: {
    checkoutSession: `${API_ROUTE_FAMILIES.billing}/checkout-session`,
    tokenPackCheckoutSession: `${API_ROUTE_FAMILIES.billing}/token-pack/checkout-session`,
    vnTokenPackCheckoutSession: `${API_ROUTE_FAMILIES.billing}/vn-token-pack/checkout-session`,
    vcTokenPackCheckoutSession: `${API_ROUTE_FAMILIES.billing}/vc-token-pack/checkout-session`,
    portalSession: `${API_ROUTE_FAMILIES.billing}/portal-session`,
    accountSummary: `${API_ROUTE_FAMILIES.billing}/account-summary`,
    cancelSubscription: `${API_ROUTE_FAMILIES.billing}/subscription/cancel`,
    resumeSubscription: `${API_ROUTE_FAMILIES.billing}/subscription/resume`,
    redeemCoupon: `${API_ROUTE_FAMILIES.billing}/coupons/redeem`,
    convertVcWallet: `${API_ROUTE_FAMILIES.billing}/wallet/vc/convert`,
    webhook: `${API_ROUTE_FAMILIES.billing}/webhook`,
  },
  publishing: {
    books: `${API_ROUTE_FAMILIES.publishing}/books`,
    importExtract: `${API_ROUTE_FAMILIES.publishing}/import/extract`,
    importSplit: `${API_ROUTE_FAMILIES.publishing}/import/split`,
    bookChapters: (bookId: string) => `${API_ROUTE_FAMILIES.publishing}/books/${encodeURIComponent(String(bookId || '').trim())}/chapters`,
    bookPublish: (bookId: string) => `${API_ROUTE_FAMILIES.publishing}/books/${encodeURIComponent(String(bookId || '').trim())}/publish`,
    chapterAudio: (bookId: string, chapterId: string) => `${API_ROUTE_FAMILIES.publishing}/books/${encodeURIComponent(String(bookId || '').trim())}/chapters/${encodeURIComponent(String(chapterId || '').trim())}/audio`,
  },
  voiceClone: {
    provider: `${API_ROUTE_FAMILIES.voiceClone}/provider`,
    status: `${API_ROUTE_FAMILIES.voiceClone}/status`,
    openvoice: `${API_ROUTE_FAMILIES.voiceClone}/openvoice`,
    render: `${API_ROUTE_FAMILIES.voiceClone}/render`,
    watermark: `${API_ROUTE_FAMILIES.voiceClone}/watermark`,
    jobs: `${API_ROUTE_FAMILIES.voiceClone}/jobs`,
    renderJob: `${API_ROUTE_FAMILIES.voiceClone}/jobs/render`,
    job: (jobId: string) => `${API_ROUTE_FAMILIES.voiceClone}/jobs/${encodeURIComponent(String(jobId || '').trim())}`,
    jobByRequest: (requestId: string) => `${API_ROUTE_FAMILIES.voiceClone}/jobs/by-request/${encodeURIComponent(String(requestId || '').trim())}`,
    cancelJob: (jobId: string) => `${API_ROUTE_FAMILIES.voiceClone}/jobs/${encodeURIComponent(String(jobId || '').trim())}/cancel`,
    separate: `${API_ROUTE_FAMILIES.voiceClone}/separate`,
    artifact: (artifactId: string) => `${API_ROUTE_FAMILIES.voiceClone}/artifacts/${encodeURIComponent(String(artifactId || '').trim())}`,
  },
  studio: {
    synthesize: `${API_ROUTE_FAMILIES.studio}/tts/synthesize`,
    longText: `${API_ROUTE_FAMILIES.studio}/tts/long-text`,
    stream: `${API_ROUTE_FAMILIES.studio}/tts/stream`,
    novelJobs: `${API_ROUTE_FAMILIES.studio}/tts/novel/jobs`,
    novelJob: (jobId: string) => `${API_ROUTE_FAMILIES.studio}/tts/novel/jobs/${encodeURIComponent(String(jobId || '').trim())}`,
    exportDrive: `${API_ROUTE_FAMILIES.studio}/tts/export/drive`,
    translateModernize: `${API_ROUTE_FAMILIES.studio}/translate/modernize`,
  },
  library: {
    books: `${API_ROUTE_FAMILIES.library}/books`,
    book: (bookId: string | number) => `${API_ROUTE_FAMILIES.library}/books/${encodeURIComponent(String(bookId || '').trim())}`,
    bookChapters: (bookId: string | number) => `${API_ROUTE_FAMILIES.library}/books/${encodeURIComponent(String(bookId || '').trim())}/chapters`,
    bookChapterAudio: (bookId: string | number, chapterId: string | number) => `${API_ROUTE_FAMILIES.library}/books/${encodeURIComponent(String(bookId || '').trim())}/chapters/${encodeURIComponent(String(chapterId || '').trim())}/audio`,
    readerObject: `${API_ROUTE_FAMILIES.library}/reader/object`,
    audioNovelJobs: `${API_ROUTE_FAMILIES.library}/audio-novel/jobs`,
    audioNovelJob: (jobId: string) => `${API_ROUTE_FAMILIES.library}/audio-novel/jobs/${encodeURIComponent(String(jobId || '').trim())}`,
    audioNovelWebSocket: `${API_ROUTE_FAMILIES.library}/audio-novel/ws`,
  },
  ops: {
    health: `${API_ROUTE_FAMILIES.ops}/health`,
    contracts: `${API_ROUTE_FAMILIES.ops}/contracts`,
  },
});
