apiVersion: v1
kind: Secret
metadata:
  name: voiceflow-redis
  namespace: voiceflow
type: Opaque
stringData:
  # Managed Redis connection string example:
  # redis://:<password>@redis-hostname:6379/0
  VF_REDIS_URL: "redis://:replace_me@managed-redis:6379/0"

