import type { LabElementStyle, LabTextStyle } from '../../../../types';

export const LAB_TEXT_PRESETS: Record<'title' | 'subtitle' | 'caption' | 'lower_third' | 'cta', LabTextStyle> = {
  title: {
    preset: 'title',
    text: 'Big headline',
    fontFamily: 'Georgia',
    fontSize: 88,
    fontWeight: 700,
    lineHeight: 1.05,
    letterSpacing: 0.5,
    textAlign: 'center',
    color: '#f8fafc',
    shadow: true,
  },
  subtitle: {
    preset: 'subtitle',
    text: 'Supporting line',
    fontFamily: 'Georgia',
    fontSize: 46,
    fontWeight: 600,
    lineHeight: 1.15,
    letterSpacing: 0.3,
    textAlign: 'center',
    color: '#e2e8f0',
    shadow: true,
  },
  caption: {
    preset: 'caption',
    text: 'Readable caption block',
    fontFamily: 'Arial',
    fontSize: 38,
    fontWeight: 700,
    lineHeight: 1.18,
    letterSpacing: 0.2,
    textAlign: 'center',
    color: '#f8fafc',
    backgroundColor: 'rgba(15,23,42,0.72)',
  },
  lower_third: {
    preset: 'lower_third',
    text: 'Speaker name',
    fontFamily: 'Arial',
    fontSize: 34,
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: 0.4,
    textAlign: 'left',
    color: '#f8fafc',
    backgroundColor: 'rgba(6,182,212,0.86)',
  },
  cta: {
    preset: 'cta',
    text: 'Watch now',
    fontFamily: 'Arial',
    fontSize: 42,
    fontWeight: 800,
    lineHeight: 1.05,
    letterSpacing: 0.8,
    textAlign: 'center',
    color: '#0f172a',
    backgroundColor: '#facc15',
  },
};

export const LAB_ELEMENT_PRESETS: Record<'accent_bar' | 'spotlight' | 'frame' | 'pill', LabElementStyle> = {
  accent_bar: {
    shape: 'bar',
    fill: 'rgba(59,130,246,0.9)',
    radius: 18,
  },
  spotlight: {
    shape: 'circle',
    fill: 'rgba(244,114,182,0.22)',
    stroke: 'rgba(244,114,182,0.52)',
    strokeWidth: 8,
  },
  frame: {
    shape: 'frame',
    fill: 'rgba(6,182,212,0.2)',
    stroke: 'rgba(6,182,212,0.9)',
    strokeWidth: 10,
  },
  pill: {
    shape: 'pill',
    fill: 'rgba(15,23,42,0.8)',
    stroke: 'rgba(248,250,252,0.38)',
    strokeWidth: 2,
  },
};
