import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';

import { DeepfakeFooterTool } from '../src/features/landing/components/DeepfakeFooterTool';
import {
  WATERMARK_CHECK_FORM_FIELD,
  WATERMARK_CHECK_PROXY_PATH,
  WATERMARK_FILE_ACCEPT,
  isSupportedWatermarkFile,
} from '../src/features/landing/components/deepfakeFooterConfig';

describe('deepfake footer tool', () => {
  it('uses the canonical Next.js watermark contract and WAV-only upload policy', () => {
    expect(WATERMARK_CHECK_PROXY_PATH).toBe('/api/v1/voice-clone/watermark');
    expect(WATERMARK_CHECK_FORM_FIELD).toBe('file');
    expect(isSupportedWatermarkFile({ name: 'proof.wav', type: 'audio/wav' })).toBe(true);
    expect(isSupportedWatermarkFile({ name: 'proof.mp3', type: 'audio/mpeg' })).toBe(false);
  });

  it('renders authenticity-only public copy', () => {
    const html = renderToStaticMarkup(<DeepfakeFooterTool />);

    expect(html).toContain('Voice authenticity check');
    expect(html).toContain('id="voice-authenticity-check"');
    expect(html).toContain('16-bit PCM WAV');
    expect(html).toContain('does not identify a speaker');
    expect(html).toContain(`accept="${WATERMARK_FILE_ACCEPT}"`);
    expect(html).not.toContain('Generated By User UID');
  });
});
